//! Never-silent dispatch over `ast.Module.body` (G2).
//!
//! Every top-level statement is **emitted**, **gapped**, or **both** (emit + sub_gaps) —
//! never neither. Ported process from mycelium-transpile `transpile::dispatch_item`, adapted
//! to Python `Stmt` variants.

use crate::emit::{class_gap_reason, emit_function, Emitted};
use crate::gap::{Category, Gap, GapReport};
use crate::map::{import_gap_reason, is_erasable_import_module, is_mappable_import, map_type_expr, rust_ident, IdentFix};
use crate::source_loc::{line_col, snippet};
use rustpython_parser::ast::{self, Ranged};
use rustpython_parser::{Parse, ParseError};
use std::collections::HashSet;
use thiserror::Error;

const SNIPPET_MAX: usize = 200;

/// Synthetic emitted-name prefix for erasable imports (no Rust residue).
/// Counted for never-silent; excluded from L1/L2 numerators in GapReport.
pub const ERASE_PREFIX: &str = "#erase:";

/// Synthetic emitted-name prefix for stdlib imports lowered to `use` lines.
pub const IMPORT_MAP_PREFIX: &str = "#import:";

#[derive(Debug, Error)]
pub enum DispatchError {
    #[error("Python parse error in {file}: {message}")]
    Parse { file: String, message: String },
}

impl From<ParseError> for DispatchError {
    fn from(e: ParseError) -> Self {
        DispatchError::Parse {
            file: "<source>".into(),
            message: e.to_string(),
        }
    }
}

/// Outcome of dispatching one top-level statement.
#[derive(Debug)]
pub enum Outcome {
    Emitted(Emitted),
    Gapped {
        category: Category,
        reason: String,
        item_name: Option<String>,
    },
}

/// Analyze Python source: produce a [`GapReport`] without requiring full emission consumers.
pub fn analyze_source(source: &str, file_label: &str) -> Result<GapReport, DispatchError> {
    let (report, _rust) = transpile_source(source, file_label, None)?;
    Ok(report)
}

/// Transpile Python source → (Rust text, gap report).
///
/// `module_name` is used only in the generated header comment.
pub fn transpile_source(
    source: &str,
    file_label: &str,
    module_name: Option<&str>,
) -> Result<(GapReport, String), DispatchError> {
    let module = ast::ModModule::parse(source, file_label).map_err(|e| DispatchError::Parse {
        file: file_label.to_string(),
        message: e.to_string(),
    })?;

    let total = module.body.len();
    // L1 counts top-level items; L2 counts every statement, nested included.
    // Both are recorded so the distance between them stays visible.
    let total_stmts = crate::parse::count_statements(&module.body);
    let mut report = GapReport::new(file_label, total).with_total_statements(total_stmts);
    let mut chunks: Vec<String> = Vec::new();

    let mod_name = module_name.unwrap_or_else(|| {
        std::path::Path::new(file_label)
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("module")
    });

    // Names that appear exactly once as a simple Name binding and are never
    // AugAssign/Delete targets are eligible for `const` emission.
    let const_eligible = module_const_eligible_names(&module.body);

    for stmt in &module.body {
        let (line, col) = line_col(source, stmt.range().start().to_u32());
        let snip = snippet(
            source,
            stmt.range().start().to_u32(),
            stmt.range().end().to_u32(),
            SNIPPET_MAX,
        );

        match dispatch_stmt(stmt, source, &const_eligible) {
            Outcome::Emitted(em) => {
                if !em.rust.is_empty() {
                    chunks.push(em.rust);
                }
                report.emitted_items.push(em.name.clone());
                for sg in em.sub_gaps {
                    report.gaps.push(Gap::new(
                        file_label,
                        line,
                        col,
                        sg.category,
                        snip.clone(),
                        sg.reason,
                        Some(em.name.clone()),
                    ));
                }
            }
            Outcome::Gapped {
                category,
                reason,
                item_name,
            } => {
                report.gaps.push(Gap::new(
                    file_label, line, col, category, snip, reason, item_name,
                ));
            }
        }
    }

    let mut rust = String::new();
    rust.push_str(&format!(
        "// Generated by py2rust from Python module: {mod_name}\n\
         // Declared emission only — review gaps in accompanying .gap.json (G2/VR-5).\n\n"
    ));
    for c in chunks {
        rust.push_str(&c);
        if !c.ends_with('\n') {
            rust.push('\n');
        }
        rust.push('\n');
    }

    debug_assert!(
        report.never_silent_holds(),
        "never-silent invariant broken for {file_label}"
    );

    Ok((report, rust))
}

/// Analyze a filesystem path (reads UTF-8).
pub fn analyze_file(path: &std::path::Path) -> Result<GapReport, DispatchError> {
    let source = std::fs::read_to_string(path).map_err(|e| DispatchError::Parse {
        file: path.display().to_string(),
        message: format!("read failed: {e}"),
    })?;
    let label = path.display().to_string();
    analyze_source(&source, &label)
}

/// Transpile a filesystem path.
pub fn transpile_file(
    path: &std::path::Path,
    module_name: Option<&str>,
) -> Result<(GapReport, String), DispatchError> {
    let source = std::fs::read_to_string(path).map_err(|e| DispatchError::Parse {
        file: path.display().to_string(),
        message: format!("read failed: {e}"),
    })?;
    let label = path.display().to_string();
    transpile_source(&source, &label, module_name)
}

/// Exhaustive-style dispatch: every `Stmt` arm records emit and/or gap.
pub fn dispatch_stmt(stmt: &ast::Stmt, source: &str, const_eligible: &HashSet<String>) -> Outcome {
    match stmt {
        ast::Stmt::FunctionDef(f) => dispatch_function(f, source),
        ast::Stmt::AsyncFunctionDef(f) => Outcome::Gapped {
            category: Category::Async,
            reason: format!(
                "async def `{}` not lowered — async/await requires manual conversion",
                f.name
            ),
            item_name: Some(f.name.to_string()),
        },
        ast::Stmt::ClassDef(c) => {
            // Classes always hard-gap (README). Extra metaprogramming signals as additional reason text.
            let gr = class_gap_reason(c);
            let mut reason = gr.reason;
            if !c.decorator_list.is_empty()
                || c.keywords.iter().any(|k| {
                    k.arg
                        .as_ref()
                        .map(|a| a.as_str() == "metaclass")
                        .unwrap_or(false)
                })
            {
                // Keep Class as primary (README) but mention metaprogramming in reason.
                reason.push_str(" [also Category::Metaprogramming signals present]");
            }
            // Single gap per top-level class (count invariant uses total_top_level once).
            Outcome::Gapped {
                category: Category::Class,
                reason,
                item_name: Some(c.name.to_string()),
            }
        }
        ast::Stmt::Try(_) | ast::Stmt::TryStar(_) => Outcome::Gapped {
            category: Category::Exception,
            reason: "try/except not lowered to Rust Result/error handling (README Exception)"
                .into(),
            item_name: None,
        },
        ast::Stmt::Raise(_) => Outcome::Gapped {
            category: Category::Exception,
            reason: "raise not lowered to Rust error propagation (README Exception)".into(),
            item_name: None,
        },
        ast::Stmt::Import(i) => {
            let names: Vec<_> = i.names.iter().map(|a| a.name.to_string()).collect();
            // typing / __future__ leave no runtime residue once annotations resolve.
            if !names.is_empty() && names.iter().all(|n| is_erasable_import_module(n)) {
                return Outcome::Emitted(Emitted {
                    name: format!("{ERASE_PREFIX}{}", names.join(",")),
                    rust: String::new(),
                    sub_gaps: vec![],
                });
            }
            // High-frequency stdlib → honest `use` scaffolding (no new crate deps).
            if !names.is_empty() {
                let mapped: Option<Vec<String>> =
                    names.iter().map(|n| is_mappable_import(n)).collect();
                if let Some(uses) = mapped {
                    return Outcome::Emitted(Emitted {
                        name: format!("{IMPORT_MAP_PREFIX}{}", names.join(",")),
                        rust: uses.join("\n") + "\n",
                        sub_gaps: vec![],
                    });
                }
            }
            // Unmapped / crate-backed: Import gap with module-specific reason.
            let reason = if names.len() == 1 {
                import_gap_reason(&names[0])
            } else {
                format!(
                    "import {} not lowered — unresolved / unmapped import (flag not guess)",
                    names.join(", ")
                )
            };
            Outcome::Gapped {
                category: Category::Import,
                reason,
                item_name: names.first().cloned(),
            }
        }
        ast::Stmt::ImportFrom(i) => {
            let mod_name = i
                .module
                .as_ref()
                .map(|m| m.to_string())
                .unwrap_or_else(|| ".".into());
            // Relative imports (level > 0) are package-local — never map to absolute
            // stdlib `use` lines even if the last segment is `sys`/`os`/…
            let level = i.level.as_ref().map(|l| l.to_u32()).unwrap_or(0);
            if level > 0 {
                return Outcome::Gapped {
                    category: Category::Import,
                    reason: format!(
                        "relative from {mod_name} import … (level={level}) not resolved — flag not guess"
                    ),
                    item_name: Some(mod_name),
                };
            }
            if is_erasable_import_module(&mod_name) {
                return Outcome::Emitted(Emitted {
                    name: format!("{ERASE_PREFIX}from:{mod_name}"),
                    rust: String::new(),
                    sub_gaps: vec![],
                });
            }
            if let Some(use_block) = is_mappable_import(&mod_name) {
                return Outcome::Emitted(Emitted {
                    name: format!("{IMPORT_MAP_PREFIX}from:{mod_name}"),
                    rust: use_block + "\n",
                    sub_gaps: vec![],
                });
            }
            Outcome::Gapped {
                category: Category::Import,
                reason: format!("from {mod_name} import … — {}", import_gap_reason(&mod_name)),
                item_name: Some(mod_name),
            }
        }
        ast::Stmt::Expr(e) => dispatch_expr_stmt(e),
        ast::Stmt::Assign(a) => {
            // Prefer the more specific Lambda category when the RHS is (or contains) a lambda.
            if contains_lambda(&a.value) {
                Outcome::Gapped {
                    category: Category::Lambda,
                    reason: "lambda assigned at module level not lowered to Rust closure (policy deferred)"
                        .into(),
                    item_name: assign_target_name(&a.targets),
                }
            } else if contains_exec_eval(&a.value) {
                Outcome::Gapped {
                    category: Category::Metaprogramming,
                    reason: "exec/eval in module-level assignment — metaprogramming not lowered"
                        .into(),
                    item_name: assign_target_name(&a.targets),
                }
            } else if let Some(em) = try_emit_module_literal_assign(a, const_eligible) {
                // Module-level `x = 1` / `s = "hi"` / … with a known literal → const item.
                Outcome::Emitted(em)
            } else {
                Outcome::Gapped {
                    category: Category::DynamicTyping,
                    reason:
                        "module-level assignment without annotation — dynamic typing not lowered"
                            .into(),
                    item_name: assign_target_name(&a.targets),
                }
            }
        }
        ast::Stmt::AnnAssign(a) => {
            // Annotated module assign with a known literal RHS → const with mapped type.
            if let Some(em) = try_emit_module_ann_assign(a, const_eligible) {
                Outcome::Emitted(em)
            } else {
                Outcome::Gapped {
                    category: Category::Other,
                    reason: "annotated module-level assignment not emitted in this phase".into(),
                    item_name: expr_name(&a.target),
                }
            }
        }
        ast::Stmt::For(_) | ast::Stmt::AsyncFor(_) | ast::Stmt::While(_) | ast::Stmt::If(_) => {
            Outcome::Gapped {
                category: Category::MultiStmtBody,
                reason: "module-level control flow not lowered in this phase".into(),
                item_name: None,
            }
        }
        ast::Stmt::With(_) | ast::Stmt::AsyncWith(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "with/async with not lowered".into(),
            item_name: None,
        },
        ast::Stmt::Match(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "match statement not lowered".into(),
            item_name: None,
        },
        ast::Stmt::Global(_) | ast::Stmt::Nonlocal(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "global/nonlocal has no direct Rust equivalent at module scope".into(),
            item_name: None,
        },
        ast::Stmt::Delete(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "del statement not lowered".into(),
            item_name: None,
        },
        ast::Stmt::AugAssign(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "augmented assignment at module level not lowered".into(),
            item_name: None,
        },
        ast::Stmt::TypeAlias(t) => {
            let name = match t.name.as_ref() {
                ast::Expr::Name(n) => Some(n.id.to_string()),
                _ => None,
            };
            Outcome::Gapped {
                category: Category::Other,
                reason: format!(
                    "type alias `{}` not lowered",
                    name.as_deref().unwrap_or("<expr>")
                ),
                item_name: name,
            }
        }
        ast::Stmt::Assert(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "assert at module level not lowered".into(),
            item_name: None,
        },
        // These are not valid module-level in normal Python modules but exist in the enum —
        // still record (never silent).
        ast::Stmt::Return(_)
        | ast::Stmt::Break(_)
        | ast::Stmt::Continue(_)
        | ast::Stmt::Pass(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "unexpected / no-op module-level statement recorded (never silent)".into(),
            item_name: None,
        },
    }
}

fn dispatch_function(f: &ast::StmtFunctionDef, source: &str) -> Outcome {
    // Decorator-heavy defs: Metaprogramming hard gap (README). Still could emit underneath;
    // honesty prefers gap the whole item when decorators alter the def surface.
    if !f.decorator_list.is_empty() {
        return Outcome::Gapped {
            category: Category::Metaprogramming,
            reason: format!(
                "def `{}` has decorator(s) — metaprogramming not lowered (README)",
                f.name
            ),
            item_name: Some(f.name.to_string()),
        };
    }

    // Body-level exec/eval → metaprogramming hard gap for the whole function.
    if body_has_exec_eval(&f.body) {
        return Outcome::Gapped {
            category: Category::Metaprogramming,
            reason: format!(
                "def `{}` uses exec/eval — metaprogramming not lowered (README)",
                f.name
            ),
            item_name: Some(f.name.to_string()),
        };
    }

    Outcome::Emitted(emit_function(f, source))
}

fn dispatch_expr_stmt(e: &ast::StmtExpr) -> Outcome {
    if contains_lambda(&e.value) {
        return Outcome::Gapped {
            category: Category::Lambda,
            reason: "lambda expression not lowered to Rust closure (policy deferred)".into(),
            item_name: None,
        };
    }
    if contains_exec_eval(&e.value) {
        return Outcome::Gapped {
            category: Category::Metaprogramming,
            reason: "exec/eval at module level — metaprogramming not lowered (README)".into(),
            item_name: None,
        };
    }
    if is_comprehension(&e.value) {
        return Outcome::Gapped {
            category: Category::Comprehension,
            reason: "comprehension not lowered in this phase".into(),
            item_name: None,
        };
    }
    Outcome::Gapped {
        category: Category::Other,
        reason: "module-level expression statement not emitted".into(),
        item_name: None,
    }
}

fn body_has_exec_eval(body: &[ast::Stmt]) -> bool {
    body.iter().any(|s| match s {
        ast::Stmt::Expr(e) => contains_exec_eval(&e.value),
        _ => false,
    })
}

fn contains_lambda(expr: &ast::Expr) -> bool {
    match expr {
        ast::Expr::Lambda(_) => true,
        ast::Expr::Call(c) => {
            contains_lambda(&c.func)
                || c.args.iter().any(contains_lambda)
                || c.keywords.iter().any(|k| contains_lambda(&k.value))
        }
        ast::Expr::BinOp(b) => contains_lambda(&b.left) || contains_lambda(&b.right),
        ast::Expr::List(l) => l.elts.iter().any(contains_lambda),
        ast::Expr::Tuple(t) => t.elts.iter().any(contains_lambda),
        ast::Expr::Dict(d) => d.values.iter().any(contains_lambda),
        _ => false,
    }
}

fn contains_exec_eval(expr: &ast::Expr) -> bool {
    match expr {
        ast::Expr::Call(c) => {
            if let ast::Expr::Name(n) = c.func.as_ref() {
                if matches!(n.id.as_str(), "exec" | "eval") {
                    return true;
                }
            }
            c.args.iter().any(contains_exec_eval)
        }
        _ => false,
    }
}

fn is_comprehension(expr: &ast::Expr) -> bool {
    matches!(
        expr,
        ast::Expr::ListComp(_)
            | ast::Expr::SetComp(_)
            | ast::Expr::DictComp(_)
            | ast::Expr::GeneratorExp(_)
    )
}

fn assign_target_name(targets: &[ast::Expr]) -> Option<String> {
    targets.first().and_then(expr_name)
}

fn expr_name(expr: &ast::Expr) -> Option<String> {
    match expr {
        ast::Expr::Name(n) => Some(n.id.to_string()),
        _ => None,
    }
}

/// Module-level `NAME = <literal>` → Rust `const` when the RHS is a known constant.
///
/// Only a single `Name` target is supported; multi-target / unpack / non-literal RHS
/// stay DynamicTyping gaps (caller). String literals lower to `&str` so the item is
/// const-legal at L3 (`String` is not a const type).
///
/// Names eligible for module-level `const`: bound exactly once via Assign/AnnAssign
/// to a single `Name` target, and never an AugAssign or Delete target.
fn module_const_eligible_names(body: &[ast::Stmt]) -> HashSet<String> {
    let mut counts: std::collections::BTreeMap<String, usize> = std::collections::BTreeMap::new();
    let mut mutated: HashSet<String> = HashSet::new();

    for stmt in body {
        match stmt {
            ast::Stmt::Assign(a) if a.targets.len() == 1 => {
                if let Some(n) = expr_name(&a.targets[0]) {
                    *counts.entry(n).or_insert(0) += 1;
                }
            }
            ast::Stmt::AnnAssign(a) => {
                if let Some(n) = expr_name(&a.target) {
                    *counts.entry(n).or_insert(0) += 1;
                }
            }
            ast::Stmt::AugAssign(a) => {
                if let Some(n) = expr_name(&a.target) {
                    mutated.insert(n);
                }
            }
            ast::Stmt::Delete(d) => {
                for t in &d.targets {
                    if let Some(n) = expr_name(t) {
                        mutated.insert(n);
                    }
                }
            }
            _ => {}
        }
    }

    counts
        .into_iter()
        .filter(|(n, c)| *c == 1 && !mutated.contains(n))
        .map(|(n, _)| n)
        .collect()
}

/// Module-level `NAME = <literal>` → Rust `const` when the RHS is a known constant
/// and the name is const-eligible (single bind, never mutated).
fn try_emit_module_literal_assign(
    a: &ast::StmtAssign,
    const_eligible: &HashSet<String>,
) -> Option<Emitted> {
    if a.targets.len() != 1 {
        return None;
    }
    let py_name = expr_name(&a.targets[0])?;
    if !const_eligible.contains(&py_name) {
        return None;
    }
    let ast::Expr::Constant(c) = a.value.as_ref() else {
        return None;
    };
    let (ty, lit) = constant_literal_ty_and_val(&c.value)?;
    Some(emit_module_const(&py_name, &ty, &lit))
}

/// Module-level `NAME: T = <literal>` → `const` when annotation + literal are known,
/// const-compatible, and the name is const-eligible.
fn try_emit_module_ann_assign(
    a: &ast::StmtAnnAssign,
    const_eligible: &HashSet<String>,
) -> Option<Emitted> {
    let py_name = expr_name(&a.target)?;
    if !const_eligible.contains(&py_name) {
        return None;
    }
    let value = a.value.as_ref()?;
    let ast::Expr::Constant(c) = value.as_ref() else {
        return None;
    };
    let mapped = map_type_expr(&a.annotation)?;
    let ty = const_compatible_type(&mapped)?;
    let lit = constant_to_rust_for_type(&c.value, ty)?;
    Some(emit_module_const(&py_name, ty, &lit))
}

fn emit_module_const(py_name: &str, ty: &str, lit: &str) -> Emitted {
    let (rs_name, fix) = rust_ident(py_name);
    let mut sub_gaps = Vec::new();
    if matches!(fix, IdentFix::Renamed) {
        sub_gaps.push(crate::gap::GapReason::new(
            Category::Other,
            format!(
                "module const `{py_name}` is a Rust keyword with no raw form; emitted as `{rs_name}`"
            ),
        ));
    }
    let rust = format!("const {rs_name}: {ty} = {lit};\n");
    Emitted {
        name: py_name.to_string(),
        rust,
        sub_gaps,
    }
}

/// Infer Rust type + literal text for a bare module-level constant RHS.
fn constant_literal_ty_and_val(c: &ast::Constant) -> Option<(String, String)> {
    match c {
        // Only ints that fit i64 — unbounded Python ints must not claim i64.
        ast::Constant::Int(i) => {
            let v: i64 = i.try_into().ok()?;
            Some(("i64".into(), v.to_string()))
        }
        ast::Constant::Float(f) => Some(("f64".into(), format!("{f:?}"))),
        ast::Constant::Bool(b) => Some(("bool".into(), b.to_string())),
        ast::Constant::Str(s) => Some(("&str".into(), format!("{:?}", s.as_str()))),
        ast::Constant::None => Some(("()".into(), "()".into())),
        _ => None,
    }
}

fn const_compatible_type(mapped: &str) -> Option<&str> {
    match mapped {
        "i64" | "f64" | "bool" | "()" => Some(mapped),
        "String" => Some("&str"),
        _ => None,
    }
}

fn constant_to_rust_for_type(c: &ast::Constant, expected: &str) -> Option<String> {
    match (c, expected) {
        (ast::Constant::Int(i), "i64") => {
            let v: i64 = i.try_into().ok()?;
            Some(v.to_string())
        }
        (ast::Constant::Int(i), "f64") => {
            let v: i64 = i.try_into().ok()?;
            Some(format!("{v}.0"))
        }
        (ast::Constant::Float(f), "f64") => Some(format!("{f:?}")),
        (ast::Constant::Bool(b), "bool") => Some(b.to_string()),
        (ast::Constant::Str(s), "&str") => Some(format!("{:?}", s.as_str())),
        (ast::Constant::None, "()") => Some("()".into()),
        _ => None,
    }
}

/// Re-export for tests that want GapReason without going through emit.
pub use crate::gap::GapReason as DispatchGapReason;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gap::Category;

    fn corpus() -> Vec<&'static str> {
        vec![
            "def add(x: int, y: int) -> int:\n    return 1\n",
            "class Foo:\n    pass\n",
            "try:\n    x = 1\nexcept Exception:\n    pass\n",
            "f = lambda x: x\n",
            "import os\n",
            "async def agen():\n    return 1\n",
            "def ok(x: int) -> int:\n    return 1\nclass C:\n    pass\nimport sys\n",
            "",
            "def bare(x):\n    return x\n",
            "def multi(x: int) -> int:\n    y = x\n    return y\n",
            "raise RuntimeError('x')\n",
            "from typing import Any\n",
            "@decorator\ndef d(x: int) -> int:\n    return x\n",
            "def ans() -> int:\n    return 42\n",
            // Module-level literals (issue #51)
            "x = 1\ns = \"hi\"\nb = True\nf = 1.5\nn = None\n",
            "COUNT: int = 3\nNAME: str = \"py2rust\"\n",
            "x = some_call()\n",
            "a = b = 1\n",
        ]
    }

    #[test]
    fn never_silent_over_fixed_corpus() {
        for src in corpus() {
            let (report, _rust) = transpile_source(src, "corpus.py", None).expect("parse ok");
            assert!(
                report.never_silent_holds(),
                "never-silent violated: top={} emitted={:?} gaps={} src={src:?}",
                report.total_top_level_items,
                report.emitted_items,
                report.gaps.len()
            );
            for g in &report.gaps {
                assert!(g.line >= 1);
                assert_eq!(g.python_construct, g.category.as_str());
            }
        }
    }

    #[test]
    fn class_exception_lambda_categories() {
        let (r, _) = transpile_source(
            "class C:\n    pass\ntry:\n    pass\nexcept:\n    pass\n(lambda x: x)\n",
            "g.py",
            None,
        )
        .unwrap();
        let cats: Vec<_> = r.gaps.iter().map(|g| g.category).collect();
        assert!(cats.contains(&Category::Class));
        assert!(cats.contains(&Category::Exception));
        assert!(cats.contains(&Category::Lambda));
    }

    #[test]
    fn emits_simple_function() {
        let (r, rust) =
            transpile_source("def answer() -> int:\n    return 42\n", "a.py", None).unwrap();
        assert!(r.emitted_items.iter().any(|n| n == "answer"));
        assert!(rust.contains("fn answer"));
        assert!(rust.contains("42"));
    }

    #[test]
    fn unannotated_records_dynamic_typing() {
        let (r, _) = transpile_source("def f(x):\n    return 1\n", "d.py", None).unwrap();
        // Emitted with DynamicTyping sub_gap(s)
        assert!(r.emitted_items.iter().any(|n| n == "f"));
        assert!(r.gaps.iter().any(|g| g.category == Category::DynamicTyping));
    }

    #[test]
    fn import_sys_emits_use_std_env() {
        let (r, rust) = transpile_source("import sys\n", "sys.py", None).unwrap();
        assert!(
            r.emitted_items
                .iter()
                .any(|n| n == &format!("{IMPORT_MAP_PREFIX}sys")),
            "sys should emit as mapped import: {:?}",
            r.emitted_items
        );
        assert!(
            !r.gaps.iter().any(|g| g.category == Category::Import),
            "mappable sys must not leave Import gap: {:?}",
            r.gaps
        );
        assert!(
            rust.contains("use std::env;"),
            "expected use std::env; got:\n{rust}"
        );
        assert!(
            rust.contains("partial"),
            "sys mapping must note partial coverage:\n{rust}"
        );
    }

    #[test]
    fn import_unknown_still_gaps() {
        let (r, rust) =
            transpile_source("import totally_unknown_mod\n", "unknown.py", None).unwrap();
        assert!(
            r.gaps.iter().any(|g| g.category == Category::Import),
            "unknown import must Import-gap: {:?}",
            r.gaps
        );
        assert!(
            !r.emitted_items
                .iter()
                .any(|n| n.starts_with(IMPORT_MAP_PREFIX)),
            "unknown must not map: {:?}",
            r.emitted_items
        );
        assert!(
            !rust.contains("use std::"),
            "unknown import must not invent use lines:\n{rust}"
        );
        let reason = &r.gaps[0].reason;
        assert!(
            reason.contains("totally_unknown_mod") && reason.contains("unmapped"),
            "reason should name the module: {reason}"
        );
    }

    #[test]
    fn import_json_gaps_with_serde_hint() {
        let (r, _) = transpile_source("import json\n", "json.py", None).unwrap();
        let gap = r
            .gaps
            .iter()
            .find(|g| g.category == Category::Import)
            .expect("json stays Import-gapped");
        assert!(
            gap.reason.contains("serde_json"),
            "json gap should point at crate: {}",
            gap.reason
        );
    }
    #[test]
    fn relative_from_sys_does_not_map_to_std() {
        // Package-relative `.sys` is NOT the stdlib — must not emit use std::env.
        let (r, rust) = transpile_source("from .sys import argv\n", "rel.py", None).unwrap();
        assert!(
            r.gaps.iter().any(|g| g.category == Category::Import),
            "relative import must Import-gap: {:?}",
            r.gaps
        );
        assert!(
            !rust.contains("use std::env"),
            "relative from .sys must not emit stdlib use:\n{rust}"
        );
        assert!(
            !r.emitted_items
                .iter()
                .any(|n| n.starts_with(IMPORT_MAP_PREFIX)),
            "relative must not #import-map: {:?}",
            r.emitted_items
        );
    }

    #[test]
    fn absolute_from_sys_maps_like_import_sys() {
        let (r, rust) = transpile_source("from sys import argv\n", "fromsys.py", None).unwrap();
        assert!(
            r.emitted_items
                .iter()
                .any(|n| n == &format!("{IMPORT_MAP_PREFIX}from:sys")),
            "absolute from sys should map: {:?}",
            r.emitted_items
        );
        assert!(
            rust.contains("use std::env;"),
            "expected use std::env; got:\n{rust}"
        );
        assert!(
            !r.gaps.iter().any(|g| g.category == Category::Import),
            "absolute from sys must not Import-gap: {:?}",
            r.gaps
        );
    }

    #[test]
    fn module_literal_assign_emits_const() {
        let src = r#"
x = 1
s = "hi"
b = True
f = 1.5
n = None
"#;
        let (r, rust) = transpile_source(src, "lit.py", Some("lit")).unwrap();
        assert!(r.never_silent_holds());
        for name in ["x", "s", "b", "f", "n"] {
            assert!(
                r.emitted_items.iter().any(|n| n == name),
                "expected emitted {name}: {:?}",
                r.emitted_items
            );
        }
        assert!(
            !r.gaps
                .iter()
                .any(|g| g.category == Category::DynamicTyping),
            "literal assigns must not DynamicTyping-gap: {:?}",
            r.gaps
        );
        assert!(rust.contains("const x: i64 = 1;"), "rust:\n{rust}");
        assert!(rust.contains("const s: &str = \"hi\";"), "rust:\n{rust}");
        assert!(rust.contains("const b: bool = true;"), "rust:\n{rust}");
        assert!(rust.contains("const f: f64 = 1.5"), "rust:\n{rust}");
        assert!(rust.contains("const n: () = ();"), "rust:\n{rust}");
    }

    #[test]
    fn module_ann_assign_literal_emits_const() {
        let src = r#"
COUNT: int = 3
NAME: str = "py2rust"
FLAG: bool = False
RATE: float = 2
"#;
        let (r, rust) = transpile_source(src, "ann.py", Some("ann")).unwrap();
        assert!(r.never_silent_holds());
        for name in ["COUNT", "NAME", "FLAG", "RATE"] {
            assert!(
                r.emitted_items.iter().any(|n| n == name),
                "expected emitted {name}: {:?}",
                r.emitted_items
            );
        }
        assert!(rust.contains("const COUNT: i64 = 3;"), "rust:\n{rust}");
        assert!(
            rust.contains("const NAME: &str = \"py2rust\";"),
            "rust:\n{rust}"
        );
        assert!(rust.contains("const FLAG: bool = false;"), "rust:\n{rust}");
        assert!(rust.contains("const RATE: f64 = 2.0;"), "rust:\n{rust}");
    }

    #[test]
    fn non_literal_module_assign_still_dynamic_typing() {
        let (r, rust) = transpile_source("x = some_call()\n", "dyn.py", None).unwrap();
        assert!(r.never_silent_holds());
        assert!(
            r.gaps
                .iter()
                .any(|g| g.category == Category::DynamicTyping),
            "gaps={:?}",
            r.gaps
        );
        assert!(!rust.contains("const x"), "rust:\n{rust}");
    }

    #[test]
    fn multi_target_assign_still_gaps() {
        let (r, _) = transpile_source("a = b = 1\n", "mt.py", None).unwrap();
        assert!(r.never_silent_holds());
        assert!(
            r.gaps
                .iter()
                .any(|g| g.category == Category::DynamicTyping),
            "gaps={:?}",
            r.gaps
        );
        assert!(r.emitted_items.is_empty());
    }
    #[test]
    fn rebind_module_name_not_const() {
        let (r, rust) = transpile_source("x = 1
x = 2
", "rebind.py", None).unwrap();
        assert!(
            !rust.contains("const x"),
            "rebound name must not emit const:
{rust}"
        );
        assert!(
            r.gaps.iter().any(|g| g.category == Category::DynamicTyping),
            "rebind should DynamicTyping-gap: {:?}",
            r.gaps
        );
    }

    #[test]
    fn oversized_int_not_i64_const() {
        let (r, rust) = transpile_source(
            "x = 99999999999999999999999999999
",
            "big.py",
            None,
        )
        .unwrap();
        assert!(
            !rust.contains("const x"),
            "out-of-range int must not claim i64 const:
{rust}"
        );
        assert!(
            r.gaps.iter().any(|g| g.category == Category::DynamicTyping),
            "oversized int should gap: {:?}",
            r.gaps
        );
    }

    #[test]
    fn augassign_blocks_const() {
        let (_r, rust) = transpile_source("x = 1
x += 1
", "aug.py", None).unwrap();
        assert!(
            !rust.contains("const x"),
            "AugAssign must block const:
{rust}"
        );
    }

}
