//! Never-silent dispatch over `ast.Module.body` (G2).
//!
//! Every top-level statement is **emitted**, **gapped**, or **both** (emit + sub_gaps) —
//! never neither. Ported process from mycelium-transpile `transpile::dispatch_item`, adapted
//! to Python `Stmt` variants.

use crate::emit::{class_gap_reason, emit_function, Emitted};
use crate::gap::{Category, Gap, GapReport};
use crate::source_loc::{line_col, snippet};
use rustpython_parser::ast::{self, Ranged};
use rustpython_parser::{Parse, ParseError};
use thiserror::Error;

const SNIPPET_MAX: usize = 200;

#[derive(Debug, Error)]
pub enum DispatchError {
    #[error("Python parse error in {file}: {message}")]
    Parse { file: String, message: String },
}

impl From<ParseError> for DispatchError {
    fn from(e: ParseError) -> Self {
        DispatchError::Parse {
            file: "<source>".into(),
            message: e.to_string(),
        }
    }
}

/// Outcome of dispatching one top-level statement.
#[derive(Debug)]
pub enum Outcome {
    Emitted(Emitted),
    Gapped {
        category: Category,
        reason: String,
        item_name: Option<String>,
    },
}

/// Analyze Python source: produce a [`GapReport`] without requiring full emission consumers.
pub fn analyze_source(source: &str, file_label: &str) -> Result<GapReport, DispatchError> {
    let (report, _rust) = transpile_source(source, file_label, None)?;
    Ok(report)
}

/// Transpile Python source → (Rust text, gap report).
///
/// `module_name` is used only in the generated header comment.
pub fn transpile_source(
    source: &str,
    file_label: &str,
    module_name: Option<&str>,
) -> Result<(GapReport, String), DispatchError> {
    let module = ast::ModModule::parse(source, file_label).map_err(|e| DispatchError::Parse {
        file: file_label.to_string(),
        message: e.to_string(),
    })?;

    let total = module.body.len();
    let mut report = GapReport::new(file_label, total);
    let mut chunks: Vec<String> = Vec::new();

    let mod_name = module_name.unwrap_or_else(|| {
        std::path::Path::new(file_label)
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("module")
    });

    for stmt in &module.body {
        let (line, col) = line_col(source, stmt.range().start().to_u32());
        let snip = snippet(
            source,
            stmt.range().start().to_u32(),
            stmt.range().end().to_u32(),
            SNIPPET_MAX,
        );

        match dispatch_stmt(stmt, source) {
            Outcome::Emitted(em) => {
                chunks.push(em.rust);
                report.emitted_items.push(em.name.clone());
                for sg in em.sub_gaps {
                    report.gaps.push(Gap::new(
                        file_label,
                        line,
                        col,
                        sg.category,
                        snip.clone(),
                        sg.reason,
                        Some(em.name.clone()),
                    ));
                }
            }
            Outcome::Gapped {
                category,
                reason,
                item_name,
            } => {
                report.gaps.push(Gap::new(
                    file_label,
                    line,
                    col,
                    category,
                    snip,
                    reason,
                    item_name,
                ));
            }
        }
    }

    let mut rust = String::new();
    rust.push_str(&format!(
        "// Generated by py2rust from Python module: {mod_name}\n\
         // Declared emission only — review gaps in accompanying .gap.json (G2/VR-5).\n\n"
    ));
    for c in chunks {
        rust.push_str(&c);
        if !c.ends_with('\n') {
            rust.push('\n');
        }
        rust.push('\n');
    }

    debug_assert!(
        report.never_silent_holds(),
        "never-silent invariant broken for {file_label}"
    );

    Ok((report, rust))
}

/// Analyze a filesystem path (reads UTF-8).
pub fn analyze_file(path: &std::path::Path) -> Result<GapReport, DispatchError> {
    let source = std::fs::read_to_string(path).map_err(|e| DispatchError::Parse {
        file: path.display().to_string(),
        message: format!("read failed: {e}"),
    })?;
    let label = path.display().to_string();
    analyze_source(&source, &label)
}

/// Transpile a filesystem path.
pub fn transpile_file(
    path: &std::path::Path,
    module_name: Option<&str>,
) -> Result<(GapReport, String), DispatchError> {
    let source = std::fs::read_to_string(path).map_err(|e| DispatchError::Parse {
        file: path.display().to_string(),
        message: format!("read failed: {e}"),
    })?;
    let label = path.display().to_string();
    transpile_source(&source, &label, module_name)
}

/// Exhaustive-style dispatch: every `Stmt` arm records emit and/or gap.
pub fn dispatch_stmt(stmt: &ast::Stmt, source: &str) -> Outcome {
    match stmt {
        ast::Stmt::FunctionDef(f) => dispatch_function(f, source),
        ast::Stmt::AsyncFunctionDef(f) => Outcome::Gapped {
            category: Category::Async,
            reason: format!(
                "async def `{}` not lowered — async/await requires manual conversion",
                f.name
            ),
            item_name: Some(f.name.to_string()),
        },
        ast::Stmt::ClassDef(c) => {
            // Classes always hard-gap (README). Extra metaprogramming signals as additional reason text.
            let gr = class_gap_reason(c);
            let mut reason = gr.reason;
            if !c.decorator_list.is_empty()
                || c.keywords.iter().any(|k| {
                    k.arg
                        .as_ref()
                        .map(|a| a.as_str() == "metaclass")
                        .unwrap_or(false)
                })
            {
                // Keep Class as primary (README) but mention metaprogramming in reason.
                reason.push_str(" [also Category::Metaprogramming signals present]");
            }
            // Single gap per top-level class (count invariant uses total_top_level once).
            Outcome::Gapped {
                category: Category::Class,
                reason,
                item_name: Some(c.name.to_string()),
            }
        }
        ast::Stmt::Try(_) | ast::Stmt::TryStar(_) => Outcome::Gapped {
            category: Category::Exception,
            reason: "try/except not lowered to Rust Result/error handling (README Exception)"
                .into(),
            item_name: None,
        },
        ast::Stmt::Raise(_) => Outcome::Gapped {
            category: Category::Exception,
            reason: "raise not lowered to Rust error propagation (README Exception)".into(),
            item_name: None,
        },
        ast::Stmt::Import(i) => {
            let names: Vec<_> = i.names.iter().map(|a| a.name.to_string()).collect();
            Outcome::Gapped {
                category: Category::Import,
                reason: format!(
                    "import {} not lowered — unresolved / unmapped import (flag not guess)",
                    names.join(", ")
                ),
                item_name: names.first().cloned(),
            }
        }
        ast::Stmt::ImportFrom(i) => {
            let mod_name = i
                .module
                .as_ref()
                .map(|m| m.to_string())
                .unwrap_or_else(|| ".".into());
            Outcome::Gapped {
                category: Category::Import,
                reason: format!(
                    "from {mod_name} import … not lowered — unresolved / unmapped import"
                ),
                item_name: Some(mod_name),
            }
        }
        ast::Stmt::Expr(e) => dispatch_expr_stmt(e),
        ast::Stmt::Assign(a) => {
            // Prefer the more specific Lambda category when the RHS is (or contains) a lambda.
            if contains_lambda(&a.value) {
                Outcome::Gapped {
                    category: Category::Lambda,
                    reason: "lambda assigned at module level not lowered to Rust closure (policy deferred)"
                        .into(),
                    item_name: assign_target_name(&a.targets),
                }
            } else if contains_exec_eval(&a.value) {
                Outcome::Gapped {
                    category: Category::Metaprogramming,
                    reason: "exec/eval in module-level assignment — metaprogramming not lowered"
                        .into(),
                    item_name: assign_target_name(&a.targets),
                }
            } else {
                Outcome::Gapped {
                    category: Category::DynamicTyping,
                    reason:
                        "module-level assignment without annotation — dynamic typing not lowered"
                            .into(),
                    item_name: assign_target_name(&a.targets),
                }
            }
        }
        ast::Stmt::AnnAssign(a) => {
            // Annotated assign at module level — still not emitted as static item yet.
            Outcome::Gapped {
                category: Category::Other,
                reason: "annotated module-level assignment not emitted in this phase".into(),
                item_name: expr_name(&a.target),
            }
        }
        ast::Stmt::For(_) | ast::Stmt::AsyncFor(_) | ast::Stmt::While(_) | ast::Stmt::If(_) => {
            Outcome::Gapped {
                category: Category::MultiStmtBody,
                reason: "module-level control flow not lowered in this phase".into(),
                item_name: None,
            }
        }
        ast::Stmt::With(_) | ast::Stmt::AsyncWith(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "with/async with not lowered".into(),
            item_name: None,
        },
        ast::Stmt::Match(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "match statement not lowered".into(),
            item_name: None,
        },
        ast::Stmt::Global(_) | ast::Stmt::Nonlocal(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "global/nonlocal has no direct Rust equivalent at module scope".into(),
            item_name: None,
        },
        ast::Stmt::Delete(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "del statement not lowered".into(),
            item_name: None,
        },
        ast::Stmt::AugAssign(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "augmented assignment at module level not lowered".into(),
            item_name: None,
        },
        ast::Stmt::TypeAlias(t) => {
            let name = match t.name.as_ref() {
                ast::Expr::Name(n) => Some(n.id.to_string()),
                _ => None,
            };
            Outcome::Gapped {
                category: Category::Other,
                reason: format!(
                    "type alias `{}` not lowered",
                    name.as_deref().unwrap_or("<expr>")
                ),
                item_name: name,
            }
        }
        ast::Stmt::Assert(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "assert at module level not lowered".into(),
            item_name: None,
        },
        // These are not valid module-level in normal Python modules but exist in the enum —
        // still record (never silent).
        ast::Stmt::Return(_)
        | ast::Stmt::Break(_)
        | ast::Stmt::Continue(_)
        | ast::Stmt::Pass(_) => Outcome::Gapped {
            category: Category::Other,
            reason: "unexpected / no-op module-level statement recorded (never silent)".into(),
            item_name: None,
        },
    }
}

fn dispatch_function(f: &ast::StmtFunctionDef, source: &str) -> Outcome {
    // Decorator-heavy defs: Metaprogramming hard gap (README). Still could emit underneath;
    // honesty prefers gap the whole item when decorators alter the def surface.
    if !f.decorator_list.is_empty() {
        return Outcome::Gapped {
            category: Category::Metaprogramming,
            reason: format!(
                "def `{}` has decorator(s) — metaprogramming not lowered (README)",
                f.name
            ),
            item_name: Some(f.name.to_string()),
        };
    }

    // Body-level exec/eval → metaprogramming hard gap for the whole function.
    if body_has_exec_eval(&f.body) {
        return Outcome::Gapped {
            category: Category::Metaprogramming,
            reason: format!(
                "def `{}` uses exec/eval — metaprogramming not lowered (README)",
                f.name
            ),
            item_name: Some(f.name.to_string()),
        };
    }

    Outcome::Emitted(emit_function(f, source))
}

fn dispatch_expr_stmt(e: &ast::StmtExpr) -> Outcome {
    if contains_lambda(&e.value) {
        return Outcome::Gapped {
            category: Category::Lambda,
            reason: "lambda expression not lowered to Rust closure (policy deferred)".into(),
            item_name: None,
        };
    }
    if contains_exec_eval(&e.value) {
        return Outcome::Gapped {
            category: Category::Metaprogramming,
            reason: "exec/eval at module level — metaprogramming not lowered (README)".into(),
            item_name: None,
        };
    }
    if is_comprehension(&e.value) {
        return Outcome::Gapped {
            category: Category::Comprehension,
            reason: "comprehension not lowered in this phase".into(),
            item_name: None,
        };
    }
    Outcome::Gapped {
        category: Category::Other,
        reason: "module-level expression statement not emitted".into(),
        item_name: None,
    }
}

fn body_has_exec_eval(body: &[ast::Stmt]) -> bool {
    body.iter().any(|s| match s {
        ast::Stmt::Expr(e) => contains_exec_eval(&e.value),
        _ => false,
    })
}

fn contains_lambda(expr: &ast::Expr) -> bool {
    match expr {
        ast::Expr::Lambda(_) => true,
        ast::Expr::Call(c) => {
            contains_lambda(&c.func)
                || c.args.iter().any(contains_lambda)
                || c.keywords.iter().any(|k| contains_lambda(&k.value))
        }
        ast::Expr::BinOp(b) => contains_lambda(&b.left) || contains_lambda(&b.right),
        ast::Expr::List(l) => l.elts.iter().any(contains_lambda),
        ast::Expr::Tuple(t) => t.elts.iter().any(contains_lambda),
        ast::Expr::Dict(d) => d.values.iter().any(contains_lambda),
        _ => false,
    }
}

fn contains_exec_eval(expr: &ast::Expr) -> bool {
    match expr {
        ast::Expr::Call(c) => {
            if let ast::Expr::Name(n) = c.func.as_ref() {
                if matches!(n.id.as_str(), "exec" | "eval") {
                    return true;
                }
            }
            c.args.iter().any(contains_exec_eval)
        }
        _ => false,
    }
}

fn is_comprehension(expr: &ast::Expr) -> bool {
    matches!(
        expr,
        ast::Expr::ListComp(_)
            | ast::Expr::SetComp(_)
            | ast::Expr::DictComp(_)
            | ast::Expr::GeneratorExp(_)
    )
}

fn assign_target_name(targets: &[ast::Expr]) -> Option<String> {
    targets.first().and_then(expr_name)
}

fn expr_name(expr: &ast::Expr) -> Option<String> {
    match expr {
        ast::Expr::Name(n) => Some(n.id.to_string()),
        _ => None,
    }
}

/// Re-export for tests that want GapReason without going through emit.
pub use crate::gap::GapReason as DispatchGapReason;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::gap::Category;

    fn corpus() -> Vec<&'static str> {
        vec![
            "def add(x: int, y: int) -> int:\n    return 1\n",
            "class Foo:\n    pass\n",
            "try:\n    x = 1\nexcept Exception:\n    pass\n",
            "f = lambda x: x\n",
            "import os\n",
            "async def agen():\n    return 1\n",
            "def ok(x: int) -> int:\n    return 1\nclass C:\n    pass\nimport sys\n",
            "",
            "def bare(x):\n    return x\n",
            "def multi(x: int) -> int:\n    y = x\n    return y\n",
            "raise RuntimeError('x')\n",
            "from typing import Any\n",
            "@decorator\ndef d(x: int) -> int:\n    return x\n",
            "def ans() -> int:\n    return 42\n",
        ]
    }

    #[test]
    fn never_silent_over_fixed_corpus() {
        for src in corpus() {
            let (report, _rust) = transpile_source(src, "corpus.py", None).expect("parse ok");
            assert!(
                report.never_silent_holds(),
                "never-silent violated: top={} emitted={:?} gaps={} src={src:?}",
                report.total_top_level_items,
                report.emitted_items,
                report.gaps.len()
            );
            for g in &report.gaps {
                assert!(g.line >= 1);
                assert_eq!(g.python_construct, g.category.as_str());
            }
        }
    }

    #[test]
    fn class_exception_lambda_categories() {
        let (r, _) = transpile_source(
            "class C:\n    pass\ntry:\n    pass\nexcept:\n    pass\n(lambda x: x)\n",
            "g.py",
            None,
        )
        .unwrap();
        let cats: Vec<_> = r.gaps.iter().map(|g| g.category).collect();
        assert!(cats.contains(&Category::Class));
        assert!(cats.contains(&Category::Exception));
        assert!(cats.contains(&Category::Lambda));
    }

    #[test]
    fn emits_simple_function() {
        let (r, rust) =
            transpile_source("def answer() -> int:\n    return 42\n", "a.py", None).unwrap();
        assert!(r.emitted_items.iter().any(|n| n == "answer"));
        assert!(rust.contains("fn answer"));
        assert!(rust.contains("42"));
    }

    #[test]
    fn unannotated_records_dynamic_typing() {
        let (r, _) = transpile_source("def f(x):\n    return 1\n", "d.py", None).unwrap();
        // Emitted with DynamicTyping sub_gap(s)
        assert!(r.emitted_items.iter().any(|n| n == "f"));
        assert!(r.gaps.iter().any(|g| g.category == Category::DynamicTyping));
    }
}
